# Generated by Django 5.2.12 on 2026-03-23 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('paternal_surname', models.CharField(max_length=50)),
                ('maternal_surname', models.CharField(max_length=50)),
                ('identity_document', models.CharField(max_length=10, unique=True)),
                ('document_type', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cod_country', models.IntegerField()),
                ('cod_university', models.IntegerField()),
                ('academic_cycle', models.CharField(max_length=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='SpecialCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'special_conditions',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('archive', models.FileField(upload_to='enrollments/')),
                ('is_active', models.BooleanField(default=True)),
                ('participant', models.ForeignKey(db_column='participant_id', on_delete=django.db.models.deletion.CASCADE, to='participant.participant')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='ParticipantSpecialCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('participant', models.ForeignKey(db_column='participant_id', on_delete=django.db.models.deletion.CASCADE, to='participant.participant')),
                ('special_condition', models.ForeignKey(db_column='special_condition_id', on_delete=django.db.models.deletion.PROTECT, to='participant.specialcondition')),
            ],
            options={
                'db_table': 'participants_special_conditions',
            },
        ),
    ]
