# Generated by Django 5.2.12 on 2026-03-23 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='registration',
            field=models.ForeignKey(db_column='registration_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='register.registration'),
        ),
    ]
