# Generated by Django 5.2.12 on 2026-03-23 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_participant_registration'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='registration',
            field=models.ForeignKey(db_column='registration_id', on_delete=django.db.models.deletion.CASCADE, to='register.registration'),
        ),
    ]
