# Generated by Django 5.2.12 on 2026-03-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_participant_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='birthday',
            field=models.DateField(),
        ),
    ]
