# Generated by Django 5.2.12 on 2026-04-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_alter_participant_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='university_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='cod_university',
            field=models.CharField(max_length=5),
        ),
    ]
