# Generated by Django 5.2.12 on 2026-04-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0006_participant_university_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='university_type',
            field=models.CharField(max_length=15),
        ),
    ]
