# Generated by Django 5.2.12 on 2026-04-05 06:30

import django.db.models.deletion
import participant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0007_alter_participant_university_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'partner_universities',
            },
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_delegate', models.CharField(max_length=15)),
                ('fullname', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('partner_university', models.ForeignKey(db_column='partner_university_id', on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to='participant.partneruniversity')),
            ],
            options={
                'db_table': 'delegates',
            },
        ),
    ]
