# Generated by Django 5.2.12 on 2026-04-05 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0008_partneruniversity_delegate'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneruniversity',
            name='quota_type',
            field=models.ForeignKey(blank=True, db_column='quota_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='register.quotatype'),
        ),
    ]
