# Generated by Django 5.2.12 on 2026-04-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0010_alter_partneruniversity_quota_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneruniversity',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
