# Generated by Django 5.2.12 on 2026-04-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0011_partneruniversity_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneruniversity',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
