# Generated by Django 5.2.12 on 2026-04-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0012_alter_partneruniversity_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneruniversity',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
