# Generated by Django 5.2.12 on 2026-04-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0013_alter_partneruniversity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneruniversity',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True, unique=True),
        ),
    ]
