# Generated by Django 5.2.12 on 2026-04-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0014_partneruniversity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='participants/'),
        ),
    ]
