# Generated by Django 5.2.12 on 2026-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0015_participant_photograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='photograph',
            field=models.ImageField(upload_to='participants/'),
        ),
    ]
