# Generated by Django 5.2.12 on 2026-04-06 00:40

import participant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0016_alter_participant_photograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='photograph',
            field=models.ImageField(upload_to=participant.models.photograph_upload_path),
        ),
    ]
