# Generated by Django 5.2.12 on 2026-04-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0017_alter_participant_photograph'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='cellphone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
