# Generated by Django 5.2.12 on 2026-04-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0018_participant_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cellphone',
            field=models.CharField(max_length=20),
        ),
    ]
