# Generated by Django 5.2.12 on 2026-04-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0019_alter_participant_cellphone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-id']},
        ),
    ]
