# Generated by Django 5.2.12 on 2026-04-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0020_alter_participant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='identity_document',
            field=models.CharField(max_length=10),
        ),
    ]
