# Generated by Django 5.2.12 on 2026-04-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0021_alter_participant_identity_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
