# Generated by Django 5.2.12 on 2026-05-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0022_alter_participant_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partneruniversity',
            options={'ordering': ['name']},
        ),
    ]
