# Generated by Django 5.2.12 on 2026-03-23 20:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pre_sales',
            },
        ),
        migrations.CreateModel(
            name='QuotaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'quota_types',
            },
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('pre_sale', models.ForeignKey(db_column='pre_sale_id', on_delete=django.db.models.deletion.PROTECT, to='register.presale')),
                ('quota_type', models.ForeignKey(db_column='quota_type_id', on_delete=django.db.models.deletion.PROTECT, to='register.quotatype')),
            ],
            options={
                'db_table': 'available_slots',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pre_sale', models.ForeignKey(db_column='pre_sale_id', on_delete=django.db.models.deletion.PROTECT, to='register.presale')),
                ('quota_type', models.ForeignKey(db_column='quota_type_id', on_delete=django.db.models.deletion.PROTECT, to='register.quotatype')),
            ],
            options={
                'db_table': 'registrations',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
                ('mount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voucher', models.FileField(upload_to='vouchers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registration', models.ForeignKey(db_column='registration_id', on_delete=django.db.models.deletion.PROTECT, to='register.registration')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('transaction', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.PROTECT, to='register.transaction')),
            ],
            options={
                'db_table': 'refunds',
            },
        ),
    ]
