# Generated by Django 5.2.12 on 2026-04-05 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('status', models.CharField(default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('quota_type', models.ForeignKey(db_column='quota_type_id', on_delete=django.db.models.deletion.PROTECT, to='register.quotatype')),
            ],
            options={
                'db_table': 'dynamic_codes',
            },
        ),
    ]
