# Generated by Django 5.2.12 on 2026-04-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_dynamiccode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamiccode',
            name='status',
            field=models.CharField(default='Disponible', max_length=20),
        ),
    ]
