# Generated by Django 5.2.12 on 2026-04-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_dynamiccode_used_at_alter_dynamiccode_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamiccode',
            options={'ordering': ['-created_at']},
        ),
    ]
