# Generated by Django 5.2.12 on 2026-04-06 00:40

import register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_dynamiccode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='voucher',
            field=models.ImageField(upload_to=register.models.voucher_upload_path),
        ),
    ]
