# Generated by Django 5.2.12 on 2026-04-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_transaction_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
