# Generated by Django 5.2.12 on 2026-05-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_transaction_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='presale',
            name='booking_mode',
            field=models.BooleanField(default=False),
        ),
    ]
