# Generated by Django 5.2.12 on 2026-05-10 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0022_alter_participant_email'),
        ('register', '0009_presale_booking_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('partner_university', models.ForeignKey(db_column='partner_university_id', on_delete=django.db.models.deletion.PROTECT, to='participant.partneruniversity')),
                ('pre_sale', models.ForeignKey(db_column='pre_sale_id', on_delete=django.db.models.deletion.PROTECT, to='register.presale')),
            ],
            options={
                'db_table': 'individual_cups',
            },
        ),
    ]
