# Generated by Django 5.2.12 on 2026-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_individual_cups'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotatype',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
