# Generated by Django 5.2.12 on 2026-05-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_quotatype_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotatype',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quotatype',
            name='category_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotatype',
            name='tier_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
