# Generated by Django 5.2.12 on 2026-03-23 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('enrollment', 'Enrollment'), ('transaction', 'Transaction'), ('registration', 'Registration')], max_length=20)),
                ('register_id', models.IntegerField()),
                ('validated', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validations',
                'unique_together': {('model', 'register_id')},
            },
        ),
    ]
