# Generated by Django 5.2.12 on 2026-04-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
