# Generated by Django 5.2.12 on 2026-04-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_validation_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
