# Generated by Django 5.2.12 on 2026-04-12 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0020_alter_participant_options'),
        ('security', '0004_validation_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('email_type', models.CharField(choices=[('inscription', 'Confirmación de inscripción'), ('payment', 'Confirmación de pago'), ('validation', 'Validación de participante'), ('reminder', 'Recordatorio'), ('custom', 'Personalizado')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido'), ('pending', 'Pendiente')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(db_column='participant_id', on_delete=django.db.models.deletion.PROTECT, to='participant.participant')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
