# Generated by Django 5.2.12 on 2026-03-23 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'activity_types',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'days',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(upload_to='speakers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'speakers',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('activity_type', models.ForeignKey(db_column='activity_type_id', on_delete=django.db.models.deletion.PROTECT, to='activity.activitytype')),
                ('day', models.ForeignKey(db_column='day_id', on_delete=django.db.models.deletion.PROTECT, to='activity.day')),
                ('speaker', models.ForeignKey(db_column='speaker_id', on_delete=django.db.models.deletion.PROTECT, to='activity.speaker')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['order'],
            },
        ),
    ]
