# Generated by Django 5.2.12 on 2026-03-27 09:04

import activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_day_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(upload_to=activity.models.speaker_upload_path),
        ),
    ]
