# Generated by Django 5.2.12 on 2026-03-23 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'networks',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('logo', models.FileField(upload_to='partners/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='PartnerNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('network', models.ForeignKey(db_column='network_id', on_delete=django.db.models.deletion.PROTECT, to='partner.network')),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.PROTECT, to='partner.partner')),
            ],
            options={
                'db_table': 'partners_networks',
            },
        ),
    ]
